# Generated by Django 3.2.6 on 2021-08-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_count', models.IntegerField()),
                ('action_date', models.DateTimeField(verbose_name='date action created')),
                ('action_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_assist.actionname')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_assist.categoryname')),
            ],
        ),
    ]
